# Load libraries
library("shiny")
library("ggplot2")
library("plotly")

hiv_df <- read.csv("./data/art_coverage_by_country_clean.csv",
  stringsAsFactors = FALSE
)

bar_chart_df <- hiv_df %>%
  group_by(WHO.Region) %>%
  select(
    Country, WHO.Region,
    Estimated.ART.coverage.among.people.living.with.HIV...._median
  ) %>%
  filter(Estimated.ART.coverage.among.people.living.with.HIV...._median
  != "NA") %>%
  rename(
    M_ART_coverage_among_living_HIV =
      Estimated.ART.coverage.among.people.living.with.HIV...._median
  )

intro <- tabPanel(
  "Intro",
  HTML(
    " <head>
    <meta charset='utf-8'>
    <link rel='preconnect' href='https://fonts.gstatic.com'>
    <link href='https://fonts.googleapis.com/css2?family=Roboto&display=swap'rel='stylesheet'>
    <link rel='stylesheet' href='styles.css'>
    <title>HIV/AIDS and ART Treatment Project</title>
  </head>
  <body>
    <header>
      <h1>HIV/AIDS and ART Treatment Dataset Introduction</h1>
    </header>
    <main>
      <img id='main' src='hiv.jpg' alt='hand holding up hiv ribbon'>
      <!-- Image taken from https://indianexpress.com/article/lifestyle/life-style/we-need-
        attention-too-the-plight-of-the-hiv-positive-community-in-india-4405035/ -->
      <section id='intro'>
      <h2>Purpose and Importance of Our Project</h2>
      <p>
        The purpose of our project is to view the extent of treatment coverage
        for HIV/AIDS in countries globally and ART treatment's impact on the
        number of people living with HIV and compare the amount of people
        living with HIV by region.
      </p>
      <h2>Leading Questions of Our Project</h2>
      <p>
        We have included several graphics of the data,
        which aims to answer a few questions about global HIV rates and
        ART treatment:
        <ol>
          <li>How do ART coverage rates for those living with HIV differ between
            countries within certain regions?</li>
          <li>What are the incidence rates and amount of deaths caused by HIV in
            countries during selected time periods?</li>
          <li>What are the estimated total number of cases of HIV, the total
            coverage, and proportion of coverage to cases in countries globally?</li>
        </ol>
      </p>
      </section>
      <section id='sources'>
        <h2>Sources of Dataset</h2>
        <p>
          The data was collected and generated by WHO and UNESCO from their public
          records on the number of people living with HIV/AIDS around the world.
          Devakumar cleaned that data from WHO and UNESCO and put the data into
          a CSV file that draws a focus on treatment statistics for those living
          with HIV/AIDS by country.
          <a href='https://www.kaggle.com/imdevskp/hiv-aids-dataset'>HIV/AIDS
          and ART Treatment</a>
        </p>
        <p>
          We added another dataset to to add latitude and longitude for all the countries:
          <a href='https://www.kaggle.com/paultimothymooney/latitude-and-longitude-for-every-country-and-state'>
            Latitude and longitude</a>
          This dataset was created by Paul Mooney and updated one year ago,
          ensuring that the data we present is still prevelant and recent. Paul
          Mooney utlized a countries csv that was published to the Google
          Public Data Explorer in the Dataset Publishing Language format.
        </p>
        <p>
          We added another dataset that tracks the amount of deathes from HIV
          from 1990 to 2017 to see how the availability of ART
          (antiretroviral therapy)
          has impacted death rates over time:
          <a href='https://ourworldindata.org/hiv-aids'>Death rates</a>
          This dataset, published by Our World in Data, includes numbers that
          were sourced from studies done by the Global Burden of Disease
          Collaborative Network.
        </p>
        <br>
      </section>
    </main>
    <br>
    <footer>
      <p>
        Created by INFO201 Group F1 &copy;2021
        All other attributions cited in page source.
      </p>
    </footer>
    <br>
  </body>"
  )
)

conclusion <- tabPanel(
  "Conclusion",
  HTML(
    "<head>
      <meta charset='utf-8'>
      <link rel='preconnect' href='https://fonts.gstatic.com'>
      <link href='https://fonts.googleapis.com/css2?family=Roboto&display=swap' rel='stylesheet'>
      <link rel='stylesheet' href='styles.css'>
      <title>HIV/AIDS and ART Treatment Dataset Introduction</title>
      </head>
      <body>
      <header>
      <h1>Project Takeaways</h1>
      </header>
      <main>
      <img id='globe' src='world.png' alt='globe and hiv ribbon'>
      <!-- Image taken from https://images.theconversation.com/files/111819/original/image-20160217
    -19239-zivpuc.png?ixlib=rb-1.1.0&q=45&auto=format&w=926&fit=clip -->
      <section id='conclusion'>
      <p>
      Through organizing, wrangling and visualizing our datasets regarding
    global HIV and ART coverage rates We have been able to make several
    major conlcusions.
    <br>
      <br>
      Based of the first bar chart on page one, we have
    found that in the Eastern Mediterranean, the country with the highest
    ART coverage among people with HIV is Jordan. In Africa, the country
    with the highest coverage is Namibia, in the Americas it is Peru, in
    Europe it is Italy, in the Western Pacific it is Australia, and lastly,
    in South-East Asia it is Thailand. Overall, the Americas has the lowest
    ART coverage for those with HIV and Africa and Europe have the highest.
    <br>
      <br>
      The map visual on the second page, gave us insight on the proportion of
    ART coverage to cases of HIV within regions globally. Through this map
    we were able to reognize that many of the regions, Africa, the Americas,
    and Western Pacific all have very similar proprotions , around 0.62-0.63.
    We also saw the the Eastern Mediterranean has the lowest proprotion of
    0.21, and Southeast Asia has the second lowest at 0.47. Europe has the
    highest proprotion at 0.71. We see that since the Eastern Mediterranean
    has the lowest proprotion of art coverage to HIV cases that countries
    within this region need to prioritize getting ART and making it more
    accessible to those suffering from HIV. From this map we also can see
    that the Eastern Mediterranean also has the lowest total cases of HIV
    out of all the regions, therefore this may be why they do not prioritize
    ART coverage as much as regions such as Africa that have incredibly high
    number of cases of HIV.
    <br>
      <br>
      Lastly, the line chart on page three shows the trends of incidences of
      HIV, death rates of HIV, and prevelance of HIV in countries globally
      between 1990-2017. We are able to infer from these charts for each country
      that while there have not been decreases in incidences or prevleance of
      HIV across time, there has been a stabilization and even decrease in
      deaths for most countries across the globe. This trend is most likely due
    to ART, which is able to help people with HIV maintain longer and healthier
    lives, despite HIV still not being able to be cured fully.
    </p>
      </section>
      </main>
      <br>
      <footer>
      <p>
      Created by INFO201 Group F1 &copy;2021
    All other attributions cited in page source.
    </p>
      </footer>
      <br>
      </body>"
  )
)

footer <- HTML(
  "<br>
  <footer class='footer'>
    <p>
      Created by INFO201 Group F1 &copy;2021
      All other attributions cited in page source.
    </p>
  </footer>
  <br>" 
)

# Bar chart stuff
bar_chart_page <- tabPanel(
  "Bar Chart",
  h2("Regional Median Estimated ART Coverage Among People Living with HIV"),
  h4("Select a Region"),
  selectInput(
    inputId = "regionselect",
    label = "Region",
    selected = "Americas",
    choices = unique(bar_chart_df$WHO.Region)
  ),
  plotlyOutput(outputId = "region_chart"),
  h3("Chart Summary:"),
  textOutput(outputId = "chartexplanation"),
  footer
)

### Map stuff
# Data for country coordinates
country_coordinates <- read.csv("./data/world_country_coordinate.csv",
  stringsAsFactors = FALSE
)

# combine data
hiv_country <- merge(hiv_df, country_coordinates,
  by = "Country",
  all.x = TRUE
)

# group_by region
hiv_region <- hiv_country %>%
  drop_na() %>%
  select(
    Country, Estimated.number.of.people.living.with.HIV_median,
    Reported.number.of.people.receiving.ART, WHO.Region, Latitude,
    Longitude
  ) %>%
  filter(Reported.number.of.people.receiving.ART != "Nodata") %>%
  mutate(Reported_receiving_art = strtoi(
    Reported.number.of.people.receiving.ART
  )) %>%
  group_by(WHO.Region) %>%
  summarize(
    total_cases = sum(
      Estimated.number.of.people.living.with.HIV_median,
      na.rm = TRUE
    ),
    total_coverage = sum(Reported_receiving_art, na.rm = TRUE),
    coverage_prop = sum(Reported_receiving_art, na.rm = TRUE) /
      sum(Estimated.number.of.people.living.with.HIV_median,
        na.rm = TRUE
      ),
    avg_lat = mean(Latitude, na.rm = TRUE),
    avg_long = mean(Longitude, na.rm = TRUE)
  )

map_page <- tabPanel(
  "Map",
  h2("View Regional data on the map")
)

region_selection <- selectInput(
  "region",
  label = h3("Choose a WHO Region"),
  choices = hiv_region$WHO.Region
)

map_chart_page <- tabPanel(
  "Map Chart",
  map_page,
  region_selection,
  h5("Click the marker that appears to view data about your selected region"),
  leafletOutput("region_map"),
  h3("Map Summary"),
  tags$div(
    id = "content-wrap",
    textOutput("map_explanation")
  ),
  footer
)

### Line Chart stuff
death_rate_df <- read.csv("./data/deaths-and-new-cases-of-hiv.csv")
death_rate_df <- death_rate_df %>%
  group_by(death_rate_df$Entity)


country_selection <- selectInput(
  "country",
  label = h3("Choose a Country"),
  choices = unique(death_rate_df$Entity)
)

years_selection <- sliderInput(
  "years",
  label = h3("Year Range"),
  min = min(death_rate_df$Year, na.rm = TRUE),
  max = max(death_rate_df$Year, na.rm = TRUE),
  value = c(
    min(death_rate_df$Year, na.rm = TRUE),
    max(death_rate_df$Year, na.rm = TRUE)
  ),
  sep = ""
)

line_chart_page <- tabPanel(
  "Line Chart",
  h2("See How Selected Countries Have Been Dealing with HIV/AIDS"),
  country_selection,
  years_selection,
  plotOutput("linechart"),
  h3("Chart Summary:"),
  textOutput(outputId = "linechartexplanation"),
  footer
)

# UI
ui <-
  fluidPage(
    includeCSS("styles.CSS"),
    navbarPage(
      tags$div(
        id = "navbar",
        "HIV Statistics"
      ),
      intro,
      bar_chart_page,
      map_chart_page,
      line_chart_page,
      conclusion
    )
  )

